@startuml
skin rose
skinparam actorstyle awesome
left to right direction

actor Player
boundary BoardView #technology
boundary CursorInput #technology
control TokenDrop #implementation
entity Cursor
entity Board

Player --> CursorInput : commits\ndrop token in\ncurrent column
CursorInput --> TokenDrop : drop
TokenDrop --> Cursor : current column?
Cursor ..> TokenDrop : current column
TokenDrop --> Board : legal move?
TokenDrop --> Board : drop token in\ncurrent column
TokenDrop -> BoardView : AddTokenIn(X)

CursorInput .l. BoardView #transparent

@enduml