@startuml
skin rose
skinparam actorstyle awesome
left to right direction

actor Player
boundary CursorInput #technology
boundary BoardView #technology
control DropToken #implementation
entity Board

Player --> CursorInput : commits\ndrop token in\ncurrent column
CursorInput --> DropToken : current column
DropToken --> Board : drop token in\ncurrent column
Board ..> DropToken : <<event>>\nTokenDroppedInColumn(X)
DropToken -> BoardView : AddTokenIn(X)

CursorInput .l. BoardView #transparent

note as N1
- How the current cursor column is stored?
- How is validated the current cursor column lets a drop?
- How is validated game is not over?
- What if drop leads to victory?
- Where is stored what player has the current turn?
end note
@enduml