@startuml
skin rose
skinparam actorstyle awesome
left to right direction

:Player:
:Match Creator: as Creator

(Move cursor\nto select\n a column) as (Cursor)
(Drop token\nin column) as (Drop)
(Select board size) as (Size)
(Start a new game) as (Start)
(Undo movement) as (Undo)

Player --> (Cursor)
Player --> (Drop)
Player --> (Undo)

Creator --> (Size)
Creator --> (Start)

Creator . Player : might be\nthe same\nperson

@enduml